# ----------------------------------------------------------------------------
#
# Package             : MACS2
# Source Repo         : https://github.com/taoliu/MACS
# Travis Job Link     : 
# Created travis.yml  : Yes
# Maintainer          : Nagesh Tarale <Nagesh.Tarale@ibm.com>
#
# Script License      : Apache 2.0
#
# ----------------------------------------------------------------------------
language: python
dist: xenial
arch:
  - amd64
  - ppc64le
python:
  - 3.6
  - 3.7
  - 3.9
  - nightly
  
script:
  - python setup.py install
