# ----------------------------------------------------------------------------
#
# Package             : MACS2
# Source Repo         : https://github.com/taoliu/MACS
# Travis Job Link     : 
# Created travis.yml  : Yes
# Maintainer          : Nagesh Tarale <Nagesh.Tarale@ibm.com>
#
# Script License      : Apache 2.0
#
# ----------------------------------------------------------------------------
sudo:
  - required

dist:
  - xenial
language: python

before_install:
  - sudo yum update -y
  - sudo yum groupinstall 'Development Tools' -y

arch:
  - amd64
  - ppc64le

python:
  - 3.6
  - 3.7
  - 3.9
  - nightly
  
install:
  - pip install macs3
  
script:
  - python setup.py install
